version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.13.0-rc.4-management
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
