server:
  port: 8099
spring:
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest

rabbitmq:
  queue:
    json:
      name: rabbit_queue_json
    name: rabbit_queue
  exchange:
    name: rabbit_exchange
  routing:
    json:
      key: rabbit_mq_routing_key_json
    key: rabbit_mq_routing_key
