server:
  port: 8099
spring:
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest

rabbitmq:
  queue:
    name: rabbit_queue
  exchange:
    name: rabbit_exchange
  routing:
    key: rabbit_mq_routing_key
